import bar from '../../../img/bar.png'

export let users =  [
    {   id:1007,
        name:"Simona",
        profit:55,
        commision:"Simona",
        view:bar,
    },
    {   id:1008,
        name:"Ariana",
        profit:45,
        commision:"Ariana",
        view:bar,
    },
    {   id:1009,
        name:"Adam",
        profit:35,
        commision:"Adam",
        view:bar,
    },
    {   id:1007,
        name:"John",
        profit:25,
        commision:"John",
        view:bar,
    },
    {   id:1007,
        name:"Garry",
        profit:15,
        commision:"Garry",
        view:bar,
    }
]